// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwgnlsrqnyugloobrsxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3Z25sc3Jxbnl1Z2xvb2Jyc3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTkzNTMsImV4cCI6MjA2NjAzNTM1M30.adv-UqRZ2lLI9cjABwMCORhugtP2-vJEMWJYnLvk1Q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);